kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
    - port: 10000
      targetPort: 10000
      name: thrift
  selector:
    component: spark-master
